# config/services.yaml
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    nom_domaine: '%env(resolve:NOM_DOMAINE)%'
    mail_from: '%env(resolve:MAIL_FROM)%'
    cv_directory: '%kernel.project_dir%/public/telecharger/cv'



services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # Nouveau service d'envoi aux admins (remplace AdminNotifier)
    App\Service\AdminBroadcastMailer:
        arguments:
            $fromAddress: '%mail_from%'
